Tugas Coding Back Propagation Fisika Komputasi

Anggota 1: Fajris Zahrotun Nihayah (10220010)

Anggota 2: Ariel Graham (10220065)


Akan dibuat program untuk menghitung besaran *weights* yang baru dari input [0, 1] dan untuk output sebesar 1 dengan *learning rate* sebesar 0.25 dan menggunakan fungsi aktivasi sigmoid.

In [1]:
import numpy as np

In [2]:
w = [[0.6, -0.1, 0.3], [-0.3, 0.4, 0.5], [0.4, 0.1, -0.2]]
x = np.array([0,1,0])
b = np.array([0,0,1]) #bias
x+b == np.add(x,b)
a = 0.25 #learning rate
k = 1 #target output

In [3]:
# Fungsi aktivasi sigmoid
def sigmoid(n):
  return 1/(1+np.exp(-1*n))



In [4]:
# Derivative dari fungsi sigmoid

def sigmoid_nd(n):
  return sigmoid(n)*(1-sigmoid(n))

In [5]:
# Perhitungan nilai input Z
input = np.zeros(3)
for i in range(2):
  for j in range(3):
    input[i] = input[i]+w[i][j]*(x+b)[j]
input

array([0.2, 0.9, 0. ])

In [6]:
# Perhitungan nilai output Z
output = np.zeros(3)
for i in range(2):
  output[i] = sigmoid(input[i])
output

array([0.549834 , 0.7109495, 0.       ])

In [10]:
# Perhitungan nilai input Y
for i in range(2):
  input[2] = input[2] + output[i]*w[2][i]
  input [2] = input[2] + x[2]*w[2][2]
input[2]

0.5820570983749832

In [11]:
# Perhitungan nilai output Y
output[2] = sigmoid(input[2])
output[2]

0.6415406071590964

In [12]:
# Perhitungan nilai d (delta)
d = np.zeros(3)
d[2] = (k-output[2])*sigmoid_nd(input[2])
d[2]

0.08243356468785928

In [13]:
# Perhitungan dw (perubahan weight)
dw = np.zeros((3,3))

# Untuk baris ketiga
for i in range(2):
  dw[2][i] = d[2]*a*output[i]
dw[2][2] = d[2]*a*(x+b)[2]
dw

# Untuk baris pertama dan kedua
for i in range(2):
  d[i] = d[2]*w[2][i]*sigmoid_nd(input[i])
d

array([0.00816147, 0.00169401, 0.08243356])

In [14]:
# Untuk perubahan weights yang lain
for i in range(2):
  for i in range(3):
    dw[i][j] = d[i]*a*(x+b)[j]
dw

array([[0.        , 0.        , 0.00204037],
       [0.        , 0.        , 0.0004235 ],
       [0.01133119, 0.01465153, 0.02060839]])

In [15]:
# Perhitungan untuk mencari weights baru
for i in range(2):
  for i in range(3):
    w[i][j] = w[i][j] + dw[i][j]
w

[[0.6, -0.1, 0.3040807346815921],
 [-0.3, 0.4, 0.5008470061439336],
 [0.4, 0.1, -0.15878321765607034]]